### ISSUE TITLE
Multiple errors on Plasma 5.12.9 (Kubuntu 18.04 with Qt Version 5.9.5)

### ISSUE THREAD

**Issue by jonnycat5000** [wwjjbb/Luna-II#12]
Tried installing both Luna-II-2.1.2.plasmoid and Luna-II-2.0.4.plasmoid but received the following error with both of them after upon installation: 

Error loading QML file: file:///home/jon/.local/share/plasma/plasmoids/org.kde.userbase.plasma.luna-ii/contents/ui/main.qml:95:9: Type LunaIcon unavailable
file:///home/jon/.local/share/plasma/plasmoids/org.kde.userbase.plasma.luna-ii/contents/ui/LunaIcon.qml:22:1: module "QtGraphicalEffects" version 1.12 is not installed

I did check to ensure that I have QtGraphicalEffects on this machine:

$ apt-file search 'qml/QtGraphicalEffects/qmldir'
qml-module-qtgraphicaleffects: /usr/lib/x86_64-linux-gnu/qt5/qml/QtGraphicalEffects/qmldir

However, reading the "qmldir" file shows everything listed with 1.0 like "Blend 1.0 Blend.qml".  

Also: after downloading Luna, the installation icon shows a red circle with a red diagonal line through it in the corner.

**Comment by wwjjbb** [comment]
2.0.4 doesn't use QtGraphicalEffects, or any of the new stuff, general idea being to leave it alone for the LTS lot. I'd expect it to work, or certainly not to kick up about QtGraphicalEffects. To try 2.0.4 cleanly - uninstall all versions of LunaII then reboot (and make sure its really gone) and install just the 2.0.4 version.

Alternatively, you could try changing 2.1.1 to use an older version of QtGraphicalEffects, since it seems Qt5.9 did in fact have a version of the QtGraphicalEffects module: 

- find the installed "contents/ui/LunaIcon.qml" file 
- find the "import QtGraphicalEffects 1.12" line
- change 1.12 to 1.0

**Comment by jonnycat5000** [comment]
Perfect, thanks WW.  I uninstalled and scrubbed the plasmoid from the directory, rebooted, and 2.0.4 is working great now.  Thanks for this app that helps me see the moon phase when the clouds are in the way!
