### ISSUE TITLE
The represented phase of the moon is one day ahead

### ISSUE THREAD

**Issue by ghost** [wwjjbb/Luna-II#2]
My location is Valencia, Spain.
The represented moon is the moon that we see the night of the next day.

**Comment by wwjjbb** [comment]
At the moment its going to be showing an earlier image in the morning compared to the one it shows in the evening. This is because it counts whole days from the **time** of last quarter to work out which image to select - the recent quarter was at about midday (12:30-ish) so that's when the day numbers are changing..

**Comment by wwjjbb** [comment]
I've taken another look at this and my comment above is not correct.

- the phase image is selected at midnight and is displayed until the following midnight. 
- the images are not right, like they've been offset a little to the right and clipped. Mare Criseum is practically touching the edge.

Needs a new base image

**Comment by wwjjbb** [comment]
Please try 2.1-beta - it should be closer to reality. I've not had much chance to see the real moon, but the plasmoid matches up reasonably with Stellarium and https://www.calsky.com/cs.cgi/Moon/1.

**Comment by wwjjbb** [comment]
Closing. Reasonably sure it got as fixed as it could be years ago. There's a limit to what's do-able with daily images anyway.
